service: ci-cd-pipeline-example

# exclude the code coverage files and circle ci files
package:
  exclude:
  - coverage/**
  - .circleci/**

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  stage: dev

# The `functions` block defines what code to deploy
functions:
  Index:
    handler: handler.Index
    events:
      - http:
          path: hello
          method: get
          cors: true
